baseURL = 'https://aadityathapa.github.io/'
languageCode = 'en-us'
title = 'Aaditya Thapa'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-8ZDGPQLE31"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Personal Blog"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a 20-year-old aspiring AI and data science enthusiast from Nepal, set to study BA Business Management with Analytics at Queen Margaret University, Edinburgh. With a background in management and computer science, Iâ€™m passionate about machine learning, data analysis, and fintech.

I enjoy writing on various topics, including tech, science, and philosophy. I'm also honing my skills in Python, SQL, Power BI, and statistics. Outside of tech, I focus on fitness and enjoy exploring new ideas through books. ðŸš€
"""

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

faviconPath = "favicon"

showFooter = false
footerContent = ""

[[params.social]]
name = "github"
url = "https://github.com/aadityathapa"

# Social icons
[[params.social]]
name = "instagram"
url = "https://www.instagram.com/aadi_tyathapa"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

[[params.menu]]
name = "library"
url = "/library"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
